// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/maciejszczurek/updatechecker/application/proto/application.proto

package com.maciejszczurek.updatechecker.application.proto;

public final class ApplicationProto {
  private ApplicationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ApplicationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.maciejszczurek.updatechecker.application.proto.Application)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string applicationType = 3;</code>
     * @return The applicationType.
     */
    java.lang.String getApplicationType();
    /**
     * <code>string applicationType = 3;</code>
     * @return The bytes for applicationType.
     */
    com.google.protobuf.ByteString
        getApplicationTypeBytes();

    /**
     * <code>string siteUrl = 4;</code>
     * @return The siteUrl.
     */
    java.lang.String getSiteUrl();
    /**
     * <code>string siteUrl = 4;</code>
     * @return The bytes for siteUrl.
     */
    com.google.protobuf.ByteString
        getSiteUrlBytes();

    /**
     * <code>string updateUrl = 5;</code>
     * @return The updateUrl.
     */
    java.lang.String getUpdateUrl();
    /**
     * <code>string updateUrl = 5;</code>
     * @return The bytes for updateUrl.
     */
    com.google.protobuf.ByteString
        getUpdateUrlBytes();

    /**
     * <code>string currentVersion = 6;</code>
     * @return The currentVersion.
     */
    java.lang.String getCurrentVersion();
    /**
     * <code>string currentVersion = 6;</code>
     * @return The bytes for currentVersion.
     */
    com.google.protobuf.ByteString
        getCurrentVersionBytes();

    /**
     * <code>bool ignored = 7;</code>
     * @return The ignored.
     */
    boolean getIgnored();

    /**
     * <code>optional int64 lastUpdate = 8;</code>
     * @return Whether the lastUpdate field is set.
     */
    boolean hasLastUpdate();
    /**
     * <code>optional int64 lastUpdate = 8;</code>
     * @return The lastUpdate.
     */
    long getLastUpdate();
  }
  /**
   * Protobuf type {@code com.maciejszczurek.updatechecker.application.proto.Application}
   */
  public static final class Application extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.maciejszczurek.updatechecker.application.proto.Application)
      ApplicationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Application.newBuilder() to construct.
    private Application(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Application() {
      name_ = "";
      applicationType_ = "";
      siteUrl_ = "";
      updateUrl_ = "";
      currentVersion_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Application();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.maciejszczurek.updatechecker.application.proto.ApplicationProto.internal_static_com_maciejszczurek_updatechecker_application_proto_Application_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.maciejszczurek.updatechecker.application.proto.ApplicationProto.internal_static_com_maciejszczurek_updatechecker_application_proto_Application_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application.class, com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APPLICATIONTYPE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object applicationType_ = "";
    /**
     * <code>string applicationType = 3;</code>
     * @return The applicationType.
     */
    @java.lang.Override
    public java.lang.String getApplicationType() {
      java.lang.Object ref = applicationType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        applicationType_ = s;
        return s;
      }
    }
    /**
     * <code>string applicationType = 3;</code>
     * @return The bytes for applicationType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getApplicationTypeBytes() {
      java.lang.Object ref = applicationType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        applicationType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SITEURL_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object siteUrl_ = "";
    /**
     * <code>string siteUrl = 4;</code>
     * @return The siteUrl.
     */
    @java.lang.Override
    public java.lang.String getSiteUrl() {
      java.lang.Object ref = siteUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        siteUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string siteUrl = 4;</code>
     * @return The bytes for siteUrl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSiteUrlBytes() {
      java.lang.Object ref = siteUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        siteUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UPDATEURL_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object updateUrl_ = "";
    /**
     * <code>string updateUrl = 5;</code>
     * @return The updateUrl.
     */
    @java.lang.Override
    public java.lang.String getUpdateUrl() {
      java.lang.Object ref = updateUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        updateUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string updateUrl = 5;</code>
     * @return The bytes for updateUrl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUpdateUrlBytes() {
      java.lang.Object ref = updateUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        updateUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CURRENTVERSION_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object currentVersion_ = "";
    /**
     * <code>string currentVersion = 6;</code>
     * @return The currentVersion.
     */
    @java.lang.Override
    public java.lang.String getCurrentVersion() {
      java.lang.Object ref = currentVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currentVersion_ = s;
        return s;
      }
    }
    /**
     * <code>string currentVersion = 6;</code>
     * @return The bytes for currentVersion.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCurrentVersionBytes() {
      java.lang.Object ref = currentVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currentVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IGNORED_FIELD_NUMBER = 7;
    private boolean ignored_ = false;
    /**
     * <code>bool ignored = 7;</code>
     * @return The ignored.
     */
    @java.lang.Override
    public boolean getIgnored() {
      return ignored_;
    }

    public static final int LASTUPDATE_FIELD_NUMBER = 8;
    private long lastUpdate_ = 0L;
    /**
     * <code>optional int64 lastUpdate = 8;</code>
     * @return Whether the lastUpdate field is set.
     */
    @java.lang.Override
    public boolean hasLastUpdate() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int64 lastUpdate = 8;</code>
     * @return The lastUpdate.
     */
    @java.lang.Override
    public long getLastUpdate() {
      return lastUpdate_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(applicationType_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, applicationType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(siteUrl_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, siteUrl_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(updateUrl_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, updateUrl_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(currentVersion_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, currentVersion_);
      }
      if (ignored_ != false) {
        output.writeBool(7, ignored_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(8, lastUpdate_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(applicationType_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, applicationType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(siteUrl_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, siteUrl_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(updateUrl_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, updateUrl_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(currentVersion_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, currentVersion_);
      }
      if (ignored_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, ignored_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, lastUpdate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application)) {
        return super.equals(obj);
      }
      com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application other = (com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getApplicationType()
          .equals(other.getApplicationType())) return false;
      if (!getSiteUrl()
          .equals(other.getSiteUrl())) return false;
      if (!getUpdateUrl()
          .equals(other.getUpdateUrl())) return false;
      if (!getCurrentVersion()
          .equals(other.getCurrentVersion())) return false;
      if (getIgnored()
          != other.getIgnored()) return false;
      if (hasLastUpdate() != other.hasLastUpdate()) return false;
      if (hasLastUpdate()) {
        if (getLastUpdate()
            != other.getLastUpdate()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + APPLICATIONTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getApplicationType().hashCode();
      hash = (37 * hash) + SITEURL_FIELD_NUMBER;
      hash = (53 * hash) + getSiteUrl().hashCode();
      hash = (37 * hash) + UPDATEURL_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateUrl().hashCode();
      hash = (37 * hash) + CURRENTVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentVersion().hashCode();
      hash = (37 * hash) + IGNORED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIgnored());
      if (hasLastUpdate()) {
        hash = (37 * hash) + LASTUPDATE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getLastUpdate());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.maciejszczurek.updatechecker.application.proto.Application}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.maciejszczurek.updatechecker.application.proto.Application)
        com.maciejszczurek.updatechecker.application.proto.ApplicationProto.ApplicationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.maciejszczurek.updatechecker.application.proto.ApplicationProto.internal_static_com_maciejszczurek_updatechecker_application_proto_Application_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.maciejszczurek.updatechecker.application.proto.ApplicationProto.internal_static_com_maciejszczurek_updatechecker_application_proto_Application_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application.class, com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application.Builder.class);
      }

      // Construct using com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        name_ = "";
        applicationType_ = "";
        siteUrl_ = "";
        updateUrl_ = "";
        currentVersion_ = "";
        ignored_ = false;
        lastUpdate_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.maciejszczurek.updatechecker.application.proto.ApplicationProto.internal_static_com_maciejszczurek_updatechecker_application_proto_Application_descriptor;
      }

      @java.lang.Override
      public com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application getDefaultInstanceForType() {
        return com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application.getDefaultInstance();
      }

      @java.lang.Override
      public com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application build() {
        com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application buildPartial() {
        com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application result = new com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.applicationType_ = applicationType_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.siteUrl_ = siteUrl_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.updateUrl_ = updateUrl_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.currentVersion_ = currentVersion_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.ignored_ = ignored_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.lastUpdate_ = lastUpdate_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application) {
          return mergeFrom((com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application other) {
        if (other == com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getApplicationType().isEmpty()) {
          applicationType_ = other.applicationType_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getSiteUrl().isEmpty()) {
          siteUrl_ = other.siteUrl_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getUpdateUrl().isEmpty()) {
          updateUrl_ = other.updateUrl_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (!other.getCurrentVersion().isEmpty()) {
          currentVersion_ = other.currentVersion_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (other.getIgnored() != false) {
          setIgnored(other.getIgnored());
        }
        if (other.hasLastUpdate()) {
          setLastUpdate(other.getLastUpdate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                applicationType_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                siteUrl_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                updateUrl_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                currentVersion_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 56: {
                ignored_ = input.readBool();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 64: {
                lastUpdate_ = input.readInt64();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object applicationType_ = "";
      /**
       * <code>string applicationType = 3;</code>
       * @return The applicationType.
       */
      public java.lang.String getApplicationType() {
        java.lang.Object ref = applicationType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          applicationType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string applicationType = 3;</code>
       * @return The bytes for applicationType.
       */
      public com.google.protobuf.ByteString
          getApplicationTypeBytes() {
        java.lang.Object ref = applicationType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          applicationType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string applicationType = 3;</code>
       * @param value The applicationType to set.
       * @return This builder for chaining.
       */
      public Builder setApplicationType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        applicationType_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string applicationType = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearApplicationType() {
        applicationType_ = getDefaultInstance().getApplicationType();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string applicationType = 3;</code>
       * @param value The bytes for applicationType to set.
       * @return This builder for chaining.
       */
      public Builder setApplicationTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        applicationType_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object siteUrl_ = "";
      /**
       * <code>string siteUrl = 4;</code>
       * @return The siteUrl.
       */
      public java.lang.String getSiteUrl() {
        java.lang.Object ref = siteUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          siteUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string siteUrl = 4;</code>
       * @return The bytes for siteUrl.
       */
      public com.google.protobuf.ByteString
          getSiteUrlBytes() {
        java.lang.Object ref = siteUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          siteUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string siteUrl = 4;</code>
       * @param value The siteUrl to set.
       * @return This builder for chaining.
       */
      public Builder setSiteUrl(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        siteUrl_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string siteUrl = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSiteUrl() {
        siteUrl_ = getDefaultInstance().getSiteUrl();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string siteUrl = 4;</code>
       * @param value The bytes for siteUrl to set.
       * @return This builder for chaining.
       */
      public Builder setSiteUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        siteUrl_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object updateUrl_ = "";
      /**
       * <code>string updateUrl = 5;</code>
       * @return The updateUrl.
       */
      public java.lang.String getUpdateUrl() {
        java.lang.Object ref = updateUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          updateUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string updateUrl = 5;</code>
       * @return The bytes for updateUrl.
       */
      public com.google.protobuf.ByteString
          getUpdateUrlBytes() {
        java.lang.Object ref = updateUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          updateUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string updateUrl = 5;</code>
       * @param value The updateUrl to set.
       * @return This builder for chaining.
       */
      public Builder setUpdateUrl(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        updateUrl_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string updateUrl = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearUpdateUrl() {
        updateUrl_ = getDefaultInstance().getUpdateUrl();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string updateUrl = 5;</code>
       * @param value The bytes for updateUrl to set.
       * @return This builder for chaining.
       */
      public Builder setUpdateUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        updateUrl_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object currentVersion_ = "";
      /**
       * <code>string currentVersion = 6;</code>
       * @return The currentVersion.
       */
      public java.lang.String getCurrentVersion() {
        java.lang.Object ref = currentVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          currentVersion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string currentVersion = 6;</code>
       * @return The bytes for currentVersion.
       */
      public com.google.protobuf.ByteString
          getCurrentVersionBytes() {
        java.lang.Object ref = currentVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currentVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string currentVersion = 6;</code>
       * @param value The currentVersion to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentVersion(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        currentVersion_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string currentVersion = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrentVersion() {
        currentVersion_ = getDefaultInstance().getCurrentVersion();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string currentVersion = 6;</code>
       * @param value The bytes for currentVersion to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        currentVersion_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private boolean ignored_ ;
      /**
       * <code>bool ignored = 7;</code>
       * @return The ignored.
       */
      @java.lang.Override
      public boolean getIgnored() {
        return ignored_;
      }
      /**
       * <code>bool ignored = 7;</code>
       * @param value The ignored to set.
       * @return This builder for chaining.
       */
      public Builder setIgnored(boolean value) {

        ignored_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>bool ignored = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearIgnored() {
        bitField0_ = (bitField0_ & ~0x00000040);
        ignored_ = false;
        onChanged();
        return this;
      }

      private long lastUpdate_ ;
      /**
       * <code>optional int64 lastUpdate = 8;</code>
       * @return Whether the lastUpdate field is set.
       */
      @java.lang.Override
      public boolean hasLastUpdate() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>optional int64 lastUpdate = 8;</code>
       * @return The lastUpdate.
       */
      @java.lang.Override
      public long getLastUpdate() {
        return lastUpdate_;
      }
      /**
       * <code>optional int64 lastUpdate = 8;</code>
       * @param value The lastUpdate to set.
       * @return This builder for chaining.
       */
      public Builder setLastUpdate(long value) {

        lastUpdate_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 lastUpdate = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastUpdate() {
        bitField0_ = (bitField0_ & ~0x00000080);
        lastUpdate_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.maciejszczurek.updatechecker.application.proto.Application)
    }

    // @@protoc_insertion_point(class_scope:com.maciejszczurek.updatechecker.application.proto.Application)
    private static final com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application();
    }

    public static com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Application>
        PARSER = new com.google.protobuf.AbstractParser<Application>() {
      @java.lang.Override
      public Application parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Application> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Application> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.maciejszczurek.updatechecker.application.proto.ApplicationProto.Application getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_maciejszczurek_updatechecker_application_proto_Application_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_maciejszczurek_updatechecker_application_proto_Application_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nDcom/maciejszczurek/updatechecker/appli" +
      "cation/proto/application.proto\0222com.maci" +
      "ejszczurek.updatechecker.application.pro" +
      "to\"\265\001\n\013Application\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002" +
      " \001(\t\022\027\n\017applicationType\030\003 \001(\t\022\017\n\007siteUrl" +
      "\030\004 \001(\t\022\021\n\tupdateUrl\030\005 \001(\t\022\026\n\016currentVers" +
      "ion\030\006 \001(\t\022\017\n\007ignored\030\007 \001(\010\022\027\n\nlastUpdate" +
      "\030\010 \001(\003H\000\210\001\001B\r\n\013_lastUpdateB\022B\020Applicatio" +
      "nProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_maciejszczurek_updatechecker_application_proto_Application_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_maciejszczurek_updatechecker_application_proto_Application_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_maciejszczurek_updatechecker_application_proto_Application_descriptor,
        new java.lang.String[] { "Id", "Name", "ApplicationType", "SiteUrl", "UpdateUrl", "CurrentVersion", "Ignored", "LastUpdate", "LastUpdate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
