name: Create release
on:
  workflow_dispatch:
  push:
    tags: ['*']

permissions:
  contents: write

jobs:
  build-jar:
    strategy:
      matrix:
        include:
          - os: 'ubuntu-latest'
            name: 'linux'
          - os: 'windows-latest'
            name: 'win'
          - os : 'macos-latest'
            name: 'macos'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: '9.1.0'
      - name: Build jar
        run: gradle bootJar
      - name: Upload Jar
        uses: actions/upload-artifact@v4
        with:
          name: update-checker-${{ matrix.name }}
          path: build/libs/update-checker-*.jar
  create-release:
    needs: [build-jar]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v6
        with:
          pattern: update-checker-*
          path: assets
          merge-multiple: true
      - name: Create release draft
        uses: MaciejSzczurek/release-action@main
        with:
          assets-directory: assets
